### ISSUE TITLE
Modify `backbone_config` structure

### ISSUE THREAD

**Issue by gitttt-1234** [talmolab/sleap-nn#142]
We need to remove the `backbone_type` parameter from `model_config` section. Instead, have a similar approach to `head_configs` section, where the keys would be the different backbone types.

```yaml
backbone_config:
    unet:
       in_channels: 1
       kernel_size: 3
       filters: 16
       filters_rate: 2
       max_stride: 16
    convnext:
    swint:

```
